name: Build APK Cleanoov

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.2'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release --split-per-abi

      - name: Upload APK arm64
        uses: actions/upload-artifact@v4
        with:
          name: cleanoov-apk-arm64
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      - name: Upload APK arm32
        uses: actions/upload-artifact@v4
        with:
          name: cleanoov-apk-arm32
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
